Merge hw1 into main
VladyslavPolushyn/altex-soft-lab pull request #1
Opened 2021-05-25 21:27 UTC by VladyslavPolushyn

First attempt at release.

2021-05-26 14:40 UTC, marynakorol requested changes

2021-05-26 14:40 UTC, marynakorol commented on hw1/assets/sass/main.sass
> +
indent doesn't match the design 
![image](https://user-images.githubusercontent.com/84564899/119674287-c2315a80-be44-11eb-8aaa-034006d4a7a4.png)

2021-05-26 19:03 UTC, VladyslavPolushyn commented on hw1/assets/js/accordion.js
> +
Thank's. Done!

2021-05-26 19:03 UTC, VladyslavPolushyn commented on hw1/assets/js/slider.js
> +	if (window.matchMedia("(min-width: 767px)").matches) {
Done.

2021-05-26 19:04 UTC, VladyslavPolushyn commented on hw1/assets/js/slider.js
> +		`);
Thank's!
I will try to fix it.

2021-05-26 19:04 UTC, VladyslavPolushyn commented on hw1/assets/js/stickyNav.js
> +const headerNav = document.querySelector('.main-header');
Done.

2021-05-26 19:04 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			h5
Thank's. Done!

2021-05-26 19:04 UTC, VladyslavPolushyn commented on hw1/index.html
> +						<h5>New York</h5>
Done.

2021-05-26 19:04 UTC, VladyslavPolushyn commented on hw1/index.html
> +				  	<h3 class="slide-item-header">Botnet</h3>
Done.

2021-05-26 19:05 UTC, VladyslavPolushyn commented on hw1/assets/js/stickyNav.js
> +	}
Thank's, I will try to fix this bug.

2021-05-26 19:05 UTC, VladyslavPolushyn commented on hw1/index.html
> +				  <input id="menu__toggle" type="checkbox" />
Done.

2021-05-26 19:09 UTC, VladyslavPolushyn commented on hw1/assets/js/stickyNav.js
> +	if (window.pageYOffset >= sticky - 65) {
Done.

2021-05-26 19:14 UTC, VladyslavPolushyn commented on hw1/assets/sass/_elements.sass
> +@mixin btnOutline
Done.

2021-05-26 19:20 UTC, VladyslavPolushyn commented on hw1/assets/sass/_fonts.sass
> +
Done.

2021-05-26 19:34 UTC, VladyslavPolushyn commented on hw1/assets/sass/_vars.sass
> +$footerBg: #F2F2F2
Done.

2021-05-26 19:39 UTC, VladyslavPolushyn commented on hw1/index.html
> +			<div class="main-header__logo"></div>
Done.

2021-05-26 19:48 UTC, VladyslavPolushyn commented on hw1/index.html
> +					    <a class="menu__item" href="#">WHY SKOUT</a>
Done.

2021-05-26 20:10 UTC, VladyslavPolushyn commented on hw1/index.html
> +					<a href="#tips" class="tab-item">tips</a>
Done

2021-05-26 20:11 UTC, VladyslavPolushyn commented on hw1/index.html
> +					<button class="accordion acc-1"><span class="accordion-header">System Patching</span> <span class="accordion-icon"></span></button>
Thank's, I will fix it.

2021-05-26 20:13 UTC, VladyslavPolushyn commented on hw1/index.html
> +				  	<img src="assets/img/arrow-left.png" alt="arrow left">
Done

2021-05-26 20:14 UTC, VladyslavPolushyn commented on hw1/index.html
> +					<button class="accordion"><span class="accordion-header">What are your system requirements?</span>  <span class="accordion-icon"></span></button>
Thank's, I will fix it.

2021-05-26 20:15 UTC, VladyslavPolushyn commented on hw1/index.html
> +						MORE QUESTIONS
done

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/index.html
> +						<a href="#">Blog</a>
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/index.html
> +						<span class="phone-number">1-855-838-4500</span>
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/index.html
> +							<span class="phone-number">+1 631-203-6600</span>
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/index.html
> +						<h5>Corporate <br>Headquarters</h5>
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/index.html
> +							<img src="assets/img/facebook.png" alt="Social Link">
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/index.html
> +					<img src="assets/img/logo-full.png" alt="Logo">
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +@import "elements"
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		background-color: #fff
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			h5
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:18 UTC, VladyslavPolushyn commented on hw1/index.html
> +						<h5>New York</h5>
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:19 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			padding: 40px 0
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:19 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		#menu__toggle:checked ~ .menu__btn > span
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:19 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +				background-color: $lightBlue
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:20 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		display: flex
Thank;s for all comments, I will fix it as soon as I can)

2021-05-26 20:20 UTC, VladyslavPolushyn commented on hw1/index.html
> +					<button class="accordion acc-3"><span class="accordion-header">Empowering Teams</span> <span class="accordion-icon"></span></button>
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:20 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			&.acc-1::before
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:20 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:20 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +					max-width: 360px
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:20 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +					max-width: 365px
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:20 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +				left: calc(50% - 770px / 2)
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:21 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +				height: 25px
No)
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:21 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +					@include btnPaddingX(22.5px)
Okay, I will remember this rule
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:21 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			bottom: -36px
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:21 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		&__slider
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:22 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		padding-top: 30px
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:22 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			.phone-number
Thank's for all comments, I will fix it as soon as I can)

2021-05-26 20:22 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +						background: url('../img/arrow-up.png') center/cover
Thank's for all comments, I will fix it as soon as I can)

2021-05-28 12:43 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +						background: url('../img/arrow-up.png') center/cover
Done.

2021-05-28 12:53 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		padding-top: 30px
Done.

2021-05-28 12:56 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			bottom: -36px
I removed the bottom rule.
Done

2021-05-28 13:00 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +				height: 25px
Done.

2021-05-28 13:07 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +				left: calc(50% - 770px / 2)
Done

2021-05-28 13:11 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +					max-width: 365px
Done

2021-05-28 13:15 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +
Done.

2021-05-28 13:19 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			&.acc-1::before
What do you mean?

2021-05-28 13:30 UTC, VladyslavPolushyn commented on hw1/index.html
> +					<button class="accordion acc-3"><span class="accordion-header">Empowering Teams</span> <span class="accordion-icon"></span></button>
Done

2021-05-28 13:31 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			&.acc-1::before
Done

2021-05-28 13:42 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		display: flex
I have not heard of such a rule before, thanks.
I hope I'll quickly retrain, thanks.

2021-05-28 13:44 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +				background-color: $lightBlue
Done, thanks

2021-05-28 13:45 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		#menu__toggle:checked ~ .menu__btn > span
Done.

2021-05-28 13:50 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			padding: 40px 0
Thank's, I'll keep it on mind.

2021-05-28 13:51 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		background-color: #fff
Done

2021-05-28 13:58 UTC, VladyslavPolushyn commented on hw1/index.html
> +							<img src="assets/img/facebook.png" alt="Social Link">
Done

2021-05-28 14:04 UTC, VladyslavPolushyn commented on hw1/index.html
> +						<h5>Corporate <br>Headquarters</h5>
Removed <br>

2021-05-28 14:07 UTC, VladyslavPolushyn commented on hw1/index.html
> +						<span class="phone-number">1-855-838-4500</span>
Done

2021-05-28 14:07 UTC, VladyslavPolushyn commented on hw1/index.html
> +							<span class="phone-number">+1 631-203-6600</span>
Done

2021-05-28 14:10 UTC, VladyslavPolushyn commented on hw1/index.html
> +	<header class="main-header">
Done

2021-05-28 14:28 UTC, VladyslavPolushyn commented on hw1/index.html
> +					<button class="accordion acc-1"><span class="accordion-header">System Patching</span> <span class="accordion-icon"></span></button>
Done

2021-05-28 14:30 UTC, VladyslavPolushyn commented on hw1/index.html
> +					<button class="accordion"><span class="accordion-header">What are your system requirements?</span>  <span class="accordion-icon"></span></button>
Done

2021-05-28 14:33 UTC, VladyslavPolushyn commented on hw1/index.html
> +						<a href="#">Blog</a>
Done

2021-05-28 14:34 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +			.phone-number
Done

2021-05-28 14:37 UTC, VladyslavPolushyn commented on hw1/assets/js/slider.js
> +		`);
I will learn the rendering and I hope I can fix it.
But I'm not ready now.

2021-05-28 18:31 UTC, VladyslavPolushyn commented on hw1/assets/js/stickyNav.js
> +	}
I will study and try this later. Thank's!

2021-05-28 18:32 UTC, VladyslavPolushyn commented on hw1/assets/sass/main.sass
> +		&__slider
I will study and try this later. Thank's!

2021-05-29 12:36 UTC, marynakorol approved these changes

2021-05-29 12:36 UTC, marynakorol commented on hw1/assets/sass/main.sass
> +		padding-top: 30px
![image](https://user-images.githubusercontent.com/84564899/120070483-71637100-c093-11eb-9c4f-bf2e53dacabd.png)

2021-05-29 12:36 UTC, marynakorol commented on hw1/assets/sass/main.sass
> +		padding-top: 30px
fix this on future

2021-05-29 12:36 UTC, merged