Marge hw2 into main
VladyslavPolushyn/altex-soft-lab pull request #2
Opened 2021-06-08 16:33 UTC by VladyslavPolushyn

2021-06-11 16:09 UTC, Maxim-Bondar commented on hw2/assets/js/fadeIn.js
> +// function onEntry(entry) {
remove useless file

2021-06-11 16:12 UTC, Maxim-Bondar commented on hw2/assets/js/mainMenu.js
> +
remove empty line

2021-06-11 16:13 UTC, Maxim-Bondar commented on hw2/assets/js/slickSlider.js
> +$(document).ready(function(){
all indets must be consistent, use prittier for example. you need to make settings for code formating

2021-06-11 16:15 UTC, Maxim-Bondar commented on hw2/assets/sass/_mixins.sass
> +	height: 40px
don't hardcode button height

2021-06-11 16:17 UTC, Maxim-Bondar commented on hw2/assets/sass/_mixins.sass
> +@mixin btnPaddingX($paddingX)
What is a profit from mexin with one css property?

2021-06-11 16:18 UTC, Maxim-Bondar commented on hw2/assets/sass/_mixins.sass
> +@mixin btnTransparent
such mixin was created for changing button background , as I understood from mixin name, but you have an extra `color` property inside

2021-06-11 16:19 UTC, Maxim-Bondar commented on hw2/assets/sass/_vars.sass
> +$gray-text-color: #7F7F7F
color variables shouldn't contain strict dependency with color value

2021-06-11 16:22 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +@import "fonts"
We don't use SASS , please use SCSS

2021-06-11 16:23 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +*
Reset and general styles must be in a separete file

2021-06-11 16:30 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +				.get-skout-btn
don't need create different classes for each buttons, you need to have one common button class and if styles are different create specific class for such button. 
Also you have a strict dependency to button text in class name, what if the text will be changed?

2021-06-11 16:31 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +		#menu__toggle:checked ~ .menu__btn > span
this implementation must be made by JS

2021-06-11 16:32 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +			p
use class selector insted of tag

2021-06-11 16:33 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +		.why-skout-btn
read comment for buttons above

2021-06-11 16:33 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +		font-size: 60px
font-size also should be taken from variables

2021-06-11 16:33 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +		// .fade-in
remove comments

2021-06-11 16:34 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +			.learn-more-btn
read about button above

2021-06-11 16:38 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +			margin: 20px auto 80px auto
magrin shouldn't be in button itself, it must be on a parent element

2021-06-11 16:39 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +		background: linear-gradient(45deg, rgb(152, 207, 195), rgb(248, 248, 250), rgb(255, 255, 255))
gradient also can be moved to the variables file

2021-06-11 16:39 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +				// background-color: transparent
remove comment

2021-06-11 16:44 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +			nav
use classes instead of tag

2021-06-11 16:45 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +@media screen and (min-width: 768px)
please format your code

2021-06-11 16:45 UTC, Maxim-Bondar commented on hw2/assets/sass/main.sass
> +			// padding-top: 200px
rwmove comments

2021-06-11 16:46 UTC, Maxim-Bondar commented on hw2/index.html
> +				  <input id="menu__toggle" type="checkbox" />
it must be a button and implemented by JS

2021-06-11 16:47 UTC, Maxim-Bondar commented on hw2/index.html
> +				  	<nav class="menu__nav" id="mobileMenu">
id also should have consistent style as class names

2021-06-11 16:49 UTC, Maxim-Bondar commented on hw2/index.html
> +					  	<button class="btn btn-transparent get-skout-btn">get skout</button>
regarding to the class naming read comment which I have left in styles file for button classes

2021-06-11 16:51 UTC, Maxim-Bondar commented on hw2/index.html
> +					<p class="main-phone">
it is also a list element

2021-06-11 16:52 UTC, Maxim-Bondar commented on hw2/index.html
> +					<div class="footer-block block-1">
block-1 is bad class name, what if such blocks will be 10 items? will you create 10 classes for each section?
also such blocks have similar stiles? why do you need such class?

2021-06-11 16:59 UTC, Maxim-Bondar requested changes
COMMON
- rename all class where you have strict dependency with content inside
- don't need to create separete classes for each button
- avoid such classes as .block-1 etc.

2021-06-13 10:32 UTC, VladyslavPolushyn commented on hw2/assets/js/fadeIn.js
> +// function onEntry(entry) {
Done

2021-06-13 10:32 UTC, VladyslavPolushyn commented on hw2/assets/js/mainMenu.js
> +
Done

2021-06-13 10:33 UTC, VladyslavPolushyn commented on hw2/assets/js/slickSlider.js
> +$(document).ready(function(){
Don't understand what exactly is wrong with indentation formatting?

2021-06-13 10:33 UTC, VladyslavPolushyn commented on hw2/assets/sass/_mixins.sass
> +	height: 40px
Done

2021-06-13 10:36 UTC, VladyslavPolushyn commented on hw2/assets/sass/_mixins.sass
> +@mixin btnPaddingX($paddingX)
I changed the mixin a bit. The point is not to repeat padding-left and padding-right. And if you use a shorthand record, then you need to specify also padding-top and padding-bottom.

2021-06-13 10:39 UTC, VladyslavPolushyn commented on hw2/assets/sass/_mixins.sass
> +@mixin btnTransparent
It was realy unnecessary. Done.

2021-06-13 10:50 UTC, VladyslavPolushyn commented on hw2/assets/sass/_vars.sass
> +$gray-text-color: #7F7F7F
Done

2021-06-13 10:55 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +*
Done

2021-06-13 11:06 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +			p
Done

2021-06-13 11:06 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +		// .fade-in
Done

2021-06-13 11:09 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +			margin: 20px auto 80px auto
Done

2021-06-13 11:15 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +		background: linear-gradient(45deg, rgb(152, 207, 195), rgb(248, 248, 250), rgb(255, 255, 255))
Done

2021-06-13 11:15 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +				// background-color: transparent
Done

2021-06-13 11:17 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +@media screen and (min-width: 768px)
Done

2021-06-13 11:17 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +			// padding-top: 200px
Done

2021-06-13 11:22 UTC, VladyslavPolushyn commented on hw2/index.html
> +				  	<nav class="menu__nav" id="mobileMenu">
Done

2021-06-13 11:31 UTC, VladyslavPolushyn commented on hw2/index.html
> +					<p class="main-phone">
Done

2021-06-16 10:10 UTC, VladyslavPolushyn commented on hw2/index.html
> +					<div class="footer-block block-1">
I agree.
Moreover these were unnecessary classes

2021-06-16 10:13 UTC, VladyslavPolushyn commented on hw2/index.html
> +					  	<button class="btn btn-transparent get-skout-btn">get skout</button>
Done

2021-06-16 10:14 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +				.get-skout-btn
Done

2021-06-16 10:18 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +			.learn-more-btn
Done

2021-06-16 10:34 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +		font-size: 60px
Done

2021-06-16 10:35 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +		.why-skout-btn
Done

2021-06-16 10:37 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +@import "fonts"
Got it.
I will take this into account in the following works.

2021-06-16 10:42 UTC, VladyslavPolushyn commented on hw2/assets/sass/main.sass
> +		#menu__toggle:checked ~ .menu__btn > span
I will take this into account in the following works. This block was html / css and I thought it was not necessary to use js.

2021-06-16 10:42 UTC, VladyslavPolushyn commented on hw2/index.html
> +				  <input id="menu__toggle" type="checkbox" />
I will take this into account in the following works. This block was html / css and I thought it was not necessary to use js.

2021-06-17 11:49 UTC, Maxim-Bondar approved these changes

2021-06-17 11:50 UTC, merged