Margin hw3 into main branch
VladyslavPolushyn/altex-soft-lab pull request #5
Opened 2021-06-27 19:15 UTC by VladyslavPolushyn

2021-07-06 11:38 UTC, marynakorol requested changes

2021-07-06 11:38 UTC, marynakorol commented on hw3/js3/main.js
> +let balance = 16273;
the sum is not correct for these denominations. Change please
e.g. you can use: let balance = 15000;

// I didn't use an object and "for..in" because indexing is important for my code
let bills = [
	[1000, 9],
	[500, 4],
	[200, 10],
	[100, 10],
	[50, 20],
	[20, 50],
	[10, 100]
];

2021-07-06 11:38 UTC, marynakorol commented on hw3/js3/main.js
> +	}
please add here a notice when the ATM can't give money because it has no denomination for this amount, e.g. when at first it was taken little denominations (10, 20, 50) and then you want to take 50uah 
![image](https://user-images.githubusercontent.com/84564899/124593250-14639380-de67-11eb-93cf-d04be3088249.png)
there is no message to understand what is the problem

2021-07-06 11:38 UTC, marynakorol commented on hw3/js3/style.css
> +	max-width: 576px;
do not use magic numbers

2021-07-06 11:38 UTC, marynakorol commented on hw3/js4/index.html
> +
please add a message inside to make it clear to see the result in console or add some visuality in html

2021-07-06 11:38 UTC, marynakorol commented on hw3/js4/index.html
> +
you can show range and result, e.g.

2021-07-07 17:44 UTC, VladyslavPolushyn commented on hw3/js1/index.html
> +	<section class="coins-area-section">
Okay

2021-07-07 17:45 UTC, VladyslavPolushyn commented on hw3/js1/main.js
> +		coinInput.classList.remove('danger-input');
Done

2021-07-07 17:48 UTC, VladyslavPolushyn commented on hw3/js1/style.css
> +	color:  ;
yeap(

2021-07-07 17:49 UTC, VladyslavPolushyn commented on hw3/js2/index.html
> +	<section class="domino-section">
Changed it to div.

2021-07-07 18:06 UTC, VladyslavPolushyn commented on hw3/js2/index.html
> +				<div class="domino"></div>
Thanks, done!

2021-07-07 18:08 UTC, VladyslavPolushyn commented on hw3/js2/main.js
> +				outputText.innerHTML = bottomCount;
Done

2021-07-07 18:08 UTC, VladyslavPolushyn commented on hw3/js2/main.js
> +				outputText.innerHTML = topCount;
Done

2021-07-07 18:08 UTC, VladyslavPolushyn commented on hw3/js2/main.js
> +	// Clear the previous genaration
Oops!
Done

2021-07-07 18:12 UTC, VladyslavPolushyn commented on hw3/js3/main.js
> +let balance = 16273;
This is not ATM money, but the client's funds.
The sum of ATM money is written to the variable 'atmMax'.

2021-07-07 18:13 UTC, VladyslavPolushyn commented on hw3/js3/style.css
> +	max-width: 576px;
Done

2021-07-07 18:34 UTC, VladyslavPolushyn commented on hw3/js4/index.html
> +
Done

2021-07-12 09:06 UTC, marynakorol commented on hw3/js3/main.js
> +let balance = 16273;
well, in this case your ATM doesn't work corretly 
![image](https://user-images.githubusercontent.com/84564899/125261066-9a6d5780-e309-11eb-8115-8c3f5c2cc837.png)

2021-07-12 09:07 UTC, marynakorol commented on hw3/js3/main.js
> +let balance = 16273;
you can't get the whole sum from the ATM

2021-07-12 09:16 UTC, VladyslavPolushyn commented on hw3/js3/main.js
> +let balance = 16273;
Okay, I will fix it

2021-07-12 09:19 UTC, marynakorol commented
please recheck the logic of ATM

2021-07-15 14:22 UTC, marynakorol approved these changes

2021-07-15 14:22 UTC, merged